### ISSUE TITLE
Just wondering why this plugin is no longer featured on the grav downloads?

### ISSUE THREAD

**Issue by MattAppleton** [OleVik/grav-plugin-fullpage#1]
Just starting to have a play, so far so good, just wondering why it is no longer on GRAV plugins — is there a compatibility issue...?

**Comment by OleVik** [comment]
This is likely because the plugin has no stable releases, as the `multilevel`-field is not stable enough for production. I will release it as v1.0.0 to make it show up in GPM, recent changes there probably hid it.
