### ISSUE TITLE
Page Typ "Fullpage" not exist

### ISSUE THREAD

**Issue by ghost** [OleVik/grav-plugin-fullpage#3]
Hello,

the plugin does not seem to work under grav CMS 1.4.2. I can not select the type "Fullpage" when creating a page because it does not exist.

**Comment by OleVik** [comment]
I cannot reproduce this in [v1.2.0](https://github.com/OleVik/grav-plugin-fullpage/releases/tag/v1.2.0) of the plugin, installed on v1.4.5 of Grav, where admins shows the following:

![image](https://user-images.githubusercontent.com/974717/40885722-335f8fc4-672c-11e8-8cc4-b16ca986338f.png)
