### ISSUE TITLE
Fullpage does not work on new clean installation of GRAV 1.5.x

### ISSUE THREAD

**Issue by RHansmann** [OleVik/grav-plugin-fullpage#7]
I just installed a new clean Grav 1.5.6 and also the Fullpage Plugin via the administration-panel->plugins. After installation I followed the guideines given here. There is no possibility to select a fullpage template while creating a new page. Are there any further installation steps not documented?

Usually Grav uses the Quark theme now as standard theme.

Can You please advise how to solve? Thank You very much.

Kind regards
Reinhard

**Comment by OleVik** [comment]
This was never added to the plugin until now, the template should be selectable in [v1.3.0](https://github.com/OleVik/grav-plugin-fullpage/releases/tag/v1.3.0).
